### ISSUE TITLE
Build fail for alsa module under Ubuntu 15.04

### ISSUE THREAD

**Issue by vilnius-leopold** [GPII/linux#70]
I don't know if you target Ubuntu, but I run Ubuntu 15.04 (with Unity) and running the build fails.
Installing the alsa dev files `libasound2-dev` fixes this issue for me.
In case someone else ran into this issue.

**Comment by javihernandez** [comment]
hey @vilnius-leopold, 

since we rely on pkg-config to resolve our build dependencies, we can't do anything to solve this problem from here. For that reason, we're trying to maintain the installation process in this [wiki page] (https://wiki.gpii.net/w/Setting_Up_Your_Development_Environment) as much as we can. Also, we have a section for [unsupported configurations](https://wiki.gpii.net/w/Setting_Up_Your_Development_Environment#Unsupported_Configurations), where you can feel free to add this issue with Ubuntu 15.04.

**Comment by vilnius-leopold** [comment]
ahh, thanks. Didn't know there was a wiki for that. Was only snooping around on github.
